[package]
name = "mc-block-stats"
description = "Minecraft block statistics analyser"
version = "0.1.0"
authors = ["brickyluke <brickyluke@gmail.com>"]
edition = "2021"
license = "Apache-2.0"

[dependencies]
clap = "2.34.0"
fastnbt = "1.3"
fastanvil = "0.23"
